name: Docker Hub Publish

on:
  push:
    tags: [ "v[0-9]+.[0-9]+.[0-9]+*" ]

  # TODO Remove once we have done a couple of releases and confirmed this is solid
  workflow_dispatch:

env:
  PLATFORMS: "linux/amd64,linux/arm64"
  DOCKERHUB_ORG: "kafkesc"
  DOCKERHUB_IMG_NAME: "ksunami"
  RELEASE_VERSION: ${{ github.ref_name }}

jobs:
  publish:
    name: Publish

    runs-on: ubuntu-latest

    steps:

      - name: Check-out
        uses: actions/checkout@v3

      - name: Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set-up Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: ${{ env.PLATFORMS }}

      - name: Build & Push
        run: |
          docker buildx build \
            --tag ${{ env.DOCKERHUB_ORG }}/${{ env.DOCKERHUB_IMG_NAME }}:latest \
            --tag ${{ env.DOCKERHUB_ORG }}/${{ env.DOCKERHUB_IMG_NAME }}:v${{ env.RELEASE_VERSION }} \
            --tag ${{ env.DOCKERHUB_ORG }}/${{ env.DOCKERHUB_IMG_NAME }}:${{ env.RELEASE_VERSION }} \
            --build-arg KSUNAMI_VERSION=${{ env.RELEASE_VERSION }} \
            --platform ${{ env.PLATFORMS }} \ 
            .
